### ISSUE TITLE
How take username,email and number from user?

### ISSUE THREAD

**Issue by Jainu-s** [prescient-automation/Bar-Bot#1]
I have seen your tutorial which is unique and none extracted data from google sheets and displayed on chat. I want to take user details like name,email and number. How do it sir?

**Comment by athenasaurav** [comment]
Hello sir,

Please check the following link:

https://github.com/prescient-automation/Bar-Bot/blob/master/actions.py

**Comment by Jainu-s** [comment]
I checked sir, I cannot find domain file.
